name: background_remover
description: A Flutter app for removing and replacing image backgrounds.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  image_picker: ^1.0.7
  image: ^4.1.7
  flutter_colorpicker: ^1.0.3
  photo_view: ^0.14.0
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  dio: ^5.4.1
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
